maxUrange: 15.0 # Hokuyo UST-20LX
maxRange: 20.0  # Hokuyo UST-20LX  使用的激光传感器的最大范围(meter)  


minimumScore: 0.0         # float 考虑到扫描匹配结果的最低分数  

linearUpdate: 0.1         #  处理所需的最小移动距离 float
angularUpdate: 0.05      #  处理所需的最小旋转角度 float

particles: 10             # 粒子滤波器中的粒子数

xmin: -10.0 # 初始地图大小(最小 x )
ymin: -10.0 # 初始地图大小(最小 y )
xmax: 10.0  # 初始地图大小(最大 x )
ymax: 10.0  # 初始地图大小(最大 y )
delta: 0.02  # 地图分辨率:距离/像素

