# http://wiki.ros.org/amcl
### Overall filter parameters
min_particles: 500    #  default 100
max_particles: 2000   #  default 5000
kld_err: 0.05         #  default 0.01  Maximum error between the true distribution and the estimated distribution 
kld_z: 0.99           #  default  0.99
update_min_d: 0.25    #  default 0.2 meters
update_min_a: 0.2     #  default  Ï€/6.0 radians
resample_interval: 1     #  default 2
transform_tolerance: 1.0     #  default   0.1 seconds   Increase tolerance because the computer can get quite busy 
recovery_alpha_slow: 0.0     #  default   0.0 (disabled)
recovery_alpha_fast: 0.0     #  default   0.0 (disabled)
gui_publish_rate:  10.0      #  default   -1.0 Hz (disabled) Publish scans from best pose at a max of 10 Hz
### Laser model parameters
laser_max_range: 12.0     #  default   -1.0
laser_max_beams: 60       #  default   30
laser_z_hit: 0.5          #  default   0.95
laser_z_short: 0.05       #  default   0.1
laser_z_max: 0.05         #  default   0.05
laser_z_rand: 0.5         #  default   0.05
laser_sigma_hit: 0.2      #  default   0.2 meters
laser_lambda_short: 0.1   #  default   0.1
laser_likelihood_max_dist: 2.0     #  default    2.0 meters
laser_model_type: likelihood_field #  default "likelihood_field" either beam, likelihood_field, or likelihood_field_prob
### Odometry model parameters
odom_model_type: diff     #  default diff    either "diff", "omni", "diff-corrected" or "omni-corrected"
odom_alpha1: 0.2          #  default  0.2
odom_alpha2: 0.2          #  default  0.2
odom_alpha3: 0.2          #  default  0.2
odom_alpha4: 0.2          #  default  0.2
odom_alpha5: 0.1          #  default  0.2




